### PR TITLE
Fix 2 issue in generated by `ags init` project

### PR DESCRIPTION
**Pull request by ReStranger**

### CODE REVIEW

**Comment by Aylur** [comment]
what issue is this trying to solve?

**Comment by ReStranger** [comment]
First commit fix this error
изображение

Second commit fix error in import in lib imports in non default project structure. For example if project located in "src" and etc

**Comment by Aylur** [comment]
The tsconfig changes are unnecessary becaues `include` defaults to `**/*`. Also including only the `@girs` dir will make it so that everything else is excluded.
I approve the `env.d.ts`, but don't change the styling

**Comment by ReStranger** [comment]
Ok, good

**Pull request closed without merging**
