### PR TITLE
v2

### LINKED ISSUE #577: Hyprland client has outdated types
Some properties of the client are either outdated or missing, they are as follows:
- Pseudo (boolean) property is missing
- fullscreen should be a number
- fullscreenMode should be fullscreenClient
- tags (string[] i think, not sure) property is missing

### PR DESCRIPTION
**Pull request by Aylur**
v2 of AGS, which is going to be a CLI tool to scaffold and run projects using [Astal](https://github.com/aylur/astal) in gjs

* setup a project directory with the `init` command which will also generate typescript types, setup env files and a tsconfig.json
* regenerate types with `types` command, when adding new libraries
* introduces a dependency on
  * go (self-explanatory, its a go program)
  * node and npm for type generation
* ~~the entry point can be either app.js, app.ts, app.jsx, app.tsx~~
* TypeScript support ootb
* JSX support ootb

Marking these as fixed/stale/obsolete as of v2

Closes Aylur/ags#577 Aylur/ags#563 Aylur/ags#554 Aylur/ags#549 Aylur/ags#547 Aylur/ags#542 Aylur/ags#541 Aylur/ags#540 Aylur/ags#537 Aylur/ags#534 Aylur/ags#533 Aylur/ags#514 Aylur/ags#497 Aylur/ags#477 Aylur/ags#472 Aylur/ags#471 Aylur/astal#79 Aylur/ags#458 Aylur/ags#446 Aylur/ags#444 Aylur/ags#443 Aylur/ags#432 Aylur/ags#418 Aylur/ags#417 Aylur/ags#416 Aylur/ags#414 Aylur/ags#413 Aylur/ags#409 Aylur/ags#408 Aylur/ags#407 Aylur/ags#403 Aylur/ags#395 Aylur/ags#391 Aylur/ags#386 Aylur/ags#379 Aylur/ags#374 Aylur/ags#372 Aylur/ags#364 Aylur/ags#362 Aylur/ags#347 Aylur/ags#338 Aylur/ags#325 Aylur/ags#317 Aylur/ags#316 Aylur/ags#314 Aylur/ags#295 Aylur/ags#294 Aylur/ags#284 Aylur/ags#275 Aylur/ags#260 Aylur/ags#235 Aylur/ags#226 Aylur/ags#224 Aylur/astal#80 Aylur/ags#188 Aylur/ags#184 Aylur/ags#64 Aylur/ags#62 Aylur/ags#246 Aylur/ags#327 Aylur/ags#346 Aylur/ags#366 Aylur/ags#367 Aylur/ags#397 Aylur/ags#436 Aylur/ags#465 Aylur/ags#458 Aylur/ags#487 Aylur/ags#494 Aylur/ags#500 Aylur/ags#508 Aylur/ags#524 Aylur/ags#548 Aylur/ags#566 Aylur/ags#571 Aylur/ags#578 Aylur/ags#585

If your issue/PR was about a feature that is still not implemented in the next version (in [Astal](https://github.com/aylur/astal)), please open it again there.

### CODE REVIEW

**Comment by adminy** [comment]
You can mark the path "astal" as external to exclude it from the bundle, which will remove this

**Comment by Joao-Queiroga** [comment]
Is there any estimate on when this will be merged?

**Comment by Aylur** [comment]
at best in a few weeks, at worse by the end of this year
few more things left to do that comes to mind right now

- [ ] vala doc comments on reference sites https://aylur.github.io/libastal/astal3
- [ ] port the examples https://aylur.github.io/ags-docs/config/examples/
- [ ] do something with the ags-docs website (I haven't decided yet)
- [ ] port the greetd ipc lib to vala

**Review by Esteban-maker66 — COMMENTED** [review]
respect to aylur.

**Pull request merged**
