### PR TITLE
Add an Easy Way to Display IP address

### PR DESCRIPTION
**Pull request by ctilley83**
Implemented functionality to get the IP address for a wired and WiFi connection. Currently the function filters out loopback and link-local addresses to ensure we return a valid address.

### CODE REVIEW

**Comment by adminy** [comment]
perhaps an unrelated question, why is it dash case? its really a pain in the butt to destructure the network.wifi object because of the dash case.

**Comment by ctilley83** [comment]
> perhaps an unrelated question, why is it dash case? its really a pain in the butt to destructure the network.wifi object because of the dash case.

Can you point to the exact code you're referring to for clarity? Are you referring to the snake case of the get accessor? I was mainly trying to be consistent with the rest of the code within the service.

**Comment by adminy** [comment]
I meant https://github.com/Aylur/ags/blob/8971835c8aefd9b6a90165c997a549264cb53310/src/service/network.ts#L91-L94

`access-points` and `icon-name`

**Comment by kotontrion** [comment]
it is a gobject convention to use kebab-case for properties. But you can access these property with snake_case and camelCase as well. So eg when deconstructing the wifi object all of these work:
```js
const nm = await Service.import('network')

const {"icon-name": icon} = nm.wifi;
const {icon_name} = nm.wifi;
const {iconName} = nm.wifi;

```

**Pull request closed without merging**
