### PR TITLE
Pam authentication

### PR DESCRIPTION
**Pull request by kotontrion**
Adds methods to Utils to be able to authenticate against Pam.

```js

Utils.authenticate("password")
  .then(res => {
    //auth was successful
  })
  .catch(logError)
Utils.authenticate_user("username", "password")
  .then(res => {
    //auth was successful
  })
  .catch(logError)

```

Note:
This is the first time I wrote a gir lib and it's been a long time since I used C, so it might be a good idea to check this a bit more in detail.

### CODE REVIEW

**Comment by kotontrion** [comment]
I just thought, this should probably made async. Depending on the pam configuration, there may be a delay when authentication fails. This will currently freeze ags for that time (I didn't test this though).

**Comment by Aylur** [comment]
It definitely needs to be async yes

**Comment by kotontrion** [comment]
I noticed an issue with this, which is quite easy fixable, I'm just writing this here to remember it.

This will create a libpam.so library in the libdir. The default libdir currently is /usr/lib, so this will overwrite the libpam.so file of the Pam package, and therefore breaking pam.
This is fixable by either renaming our Pam module to something like libagspam.so or something similar, or even better use /usr/lib/ags as the default libdir. This is already done by the AUR package, and the reason I didn't notice this issue until now.

**Comment by Aylur** [comment]
I think its fine, Gvc is also installed there, and we didn't get any feedback about it being an issue
But if we decide to rename it, I would like to avoid having ags in its name, because the eventual rebranding for the gtk4 version. libpamauth or maybe something like libgutils because I would also like to support input inhibiting sometime which needs to be in c too

**Pull request merged**
