### PR TITLE
Create a circular progress widget like in eww

### PR DESCRIPTION
**Pull request by AhmedSaadi0**
### example
        const { Button, Label, CircularProgress } = ags.Widget
    const { Battery } = ags.Service

    const label = Label({
        className: "battery-inner",
        label: ""
    })

    export const BatteryWidget = () => CircularProgress({
        className: "battery",
        childWidget: Button({
            className: "unset",
            child: label
        }),
        connections: [
            [Battery, batteryProgress => {

                if (Battery.charging) {
                    label.className = "battery-inner-charging";
                } else {
                    label.className = "battery-inner";
                }
                batteryProgress.updateProgress(Battery.percent);
            }],
        ],
    });

### css code
    .battery {
        background-color: #431d61;
        color: #FDEAB0;
        min-width: 30px;
        min-height: 20px;
        font-size: 4px;
    }

    @keyframes colorChange {
        0% {
            color: #431d61;
        }

        50% {
            color: #FFEDAE;
        }

        100% {
            color: #431d61;
        }
    }

    .battery-inner {
        color: #FFEDAE;
        margin-top: 0.2em;
        margin-right: 0.3em;
        margin-bottom: 0.2em;
        min-width: 2px;
        font-size: 2.5em;
    }

    .battery-inner-charging {
        color: #FFEDAE;
        margin-top: 0.2em;
        margin-right: 0.3em;
        margin-bottom: 0.2em;
        min-width: 2px;
        font-size: 2.5em;
        animation: colorChange 2s infinite;
    }

2023-09-09-030011_hyprshot

### CODE REVIEW

**Comment by Aylur** [comment]
It should be a subclass of Gtk.Bin and use the child prop instead of a custom childWidget.
Why are you saving classNames in the constructor?
Instead of an updateProgress method, the angle and progress (which I feel should be renamed to value) should be defined properties in GObject.registerClass

**Comment by AhmedSaadi0** [comment]
Ok i've removed the classNames from constructor, changed updateProgress into value, added angle and value in properties, and changed it to Gtk.Bin, but I got some problems when I add child 

when I create an object using
    
    const label = Label({
        className: "battery-inner",
        label: "󰄯"
    })

    const button = Button({
        className: "unset",
        child: label,
    });

    export const BatteryWidget = () => CircularProgress({
        className: "battery",
        child: button, // does not recognized in CircularProgress
        connections: [
            [battery, batteryProgress =>{
                if (battery.charging) {
                    label.className = "battery-inner-charging";
                } else {
                    label.className = "battery-inner";
                }
                batteryProgress.value = battery.percent;
            }],
        ],
    });

and when I do like this it recognizes it but it gives warnings saying the widget is already inside a container
                
    batteryProgress.add(Button({
                     className: "unset",
                     child: label
                }));

this is the full warning 
    
    (ags:241472): Gtk-WARNING **: 01:38:19.679: Attempting to add a widget with type AgsLabel to a container of type AgsButton, but the widget is already inside a container of type AgsButton, please remove the widget from its existing container first.

    (ags:241472): Gtk-WARNING **: 01:38:19.679: Attempting to add a widget with type AgsButton to a CircularProgressBarBin, but as a GtkBin subclass a CircularProgressBarBin can only contain one widget at a time; it already contains a widget of type AgsButton

What could be the problem ?
what should I do ?

**Comment by Aylur** [comment]
wrong commit message oops, anyway, I added margin, clockwise and a half done start_at support

**Comment by Aylur** [comment]
filling the background if there is no child is unnecessary since you can set font-size to half of the allocated size, so now its possilbe to have a ring shape without adding a child

**Pull request merged**
