### PR TITLE
support nix

### PR DESCRIPTION
**Pull request by dongsu8142**
Made me support nix to build on nixos. #8

### CODE REVIEW

**Comment by dongsu8142** [comment]
If there's a problem, I'll fix it

**Comment by Aylur** [comment]
how does socat, networkmanager, and gnomebluetooth work even though they are not listed as build inputs?

**Comment by dongsu8142** [comment]
For socat, it must be installed separately, and NetworkManager and gnomebluetooth are included in [gtk-gjs](https://github.com/dongsu8142/nur/blob/master/pkgs/gtk-gjs/default.nix)

**Comment by dongsu8142** [comment]
I tested it on my computer and it worked fine, but it needs to be tested in more places.

**Comment by Aylur** [comment]
It works on mine too, but I think the bluetooth works because we have gnomebluetooth already installed, same for nm and socat too
but I guess they are installed by deafult on pretty much every distro

**Pull request merged**
