### PR TITLE
added recursive option to monitorFile

### PR DESCRIPTION
**Pull request by NicolaiVdS**
added functionality to monitorFile to be recursive 

NOTE: Recursive is true by default

### CODE REVIEW

**Comment by Aylur** [comment]
small thing, but maybe we should have this instead
```ts
export function monitorFile(
    path: string,
    callback: (file: Gio.File, event: Gio.FileMonitorEvent) => void,
    options?: { flags: Gio.FileMonitorFlags, recursive: boolean },
)
```

**Comment by NicolaiVdS** [comment]
> small thing, but maybe we should have this instead
> 
> ```ts
> export function monitorFile(
>     path: string,
>     callback: (file: Gio.File, event: Gio.FileMonitorEvent) => void,
>     options?: { flags: Gio.FileMonitorFlags, recursive: boolean },
> )
> ```

Ok i can see the point in using options but should flags still be used since 
```ts
// FIXME: remove the checking in the next release
  // @ts-expect-error
  if (options?.flags === "file" || options?.flags === "directory") {
    throw Error(
      `${options?.flags}` +
        " passed as a parameter in `monitorFile`. " +
        "Specifying the type is no longer required."
    );
  }
```

**Comment by Aylur** [comment]
that check was there because the third parameter used to be `"file" | "directory"`, but it was removed with #302
this time, since it will be another breaking change, we need to update it to check if the third parameter is a number (Gio.FileMonitorFlags) and console.warn about it being changed to an options object

**Comment by NicolaiVdS** [comment]
> that check was there because the third parameter used to be `"file" | "directory"`, but it was removed with #302 this time, since it will be another breaking change, we need to update it to check if the third parameter is a number (Gio.FileMonitorFlags) and console.warn about it being changed to an options object

added the requested changes

**Pull request merged**
