### PR TITLE
overwrite toJSON to include ParamSpecced properties

### PR DESCRIPTION
**Pull request by kotontrion**
this PR overwrites the toJSON method of widgets, services and variables to include GObject properties to make debuggin easier.
toJSON currently only includes these paramspecced properties, and no other properties, but those could be added. For example the poll/listen of the variable might be useful.

### CODE REVIEW

**Comment by Aylur** [comment]
I didn't know you could query ParamsPspecs from the constructor, this is really useful
I propose this
```js
GObject.Object.prototype.toJSON = function() {
    const result = {};
    const filter = ['parent', 'window', 'font-options'];
    const props = this.constructor
        .list_properties()
        .filter(p => !filter.includes(p.name))

    props.forEach(p => {
        try {
            result[p.name] = this[p.name];
        }
        catch (e) {
            logError(e, p.name);
        }
    });

    return result;
}
```

Although printing a JSON this way is unreadable imo, since there are a lot of properties
For Variables and Services maybe we could override it so it only prints the properties that has to do with the Service
We could also ParamSpec `listen` and `poll` for Variables, but thats for another PR

**Comment by kotontrion** [comment]
> I propose this

done.

> I didn't know you could query ParamsPspecs from the constructor, this is really useful

I'm not sure how to make ts happy about this though

Yeah the output can get quite long, especially on the Hyprland service, as here all clients are printed as well, and on Widgets with many children. But on the other hand, these information can be quite useful.
I think we should output everything, then the users can filter out the information of interest themself. That's better than not getting possible important information, IMO. As this is intended mostly for debugging purposes, the more data you have the better.

**Comment by Aylur** [comment]
>I'm not sure how to make ts happy about this though

There is no way to let TypeScript know about this, and its bad practice to mess with prototypes in general (not in our case, since its a language binding). We should probably move this into `overrides.ts` file though
If you take a look at GJS source code its waaay too cursed.

>better than not getting possible important information

agreed.

I'll test it a bit further to make sure there is no infinite recursion, there is probably a few more props like `font-options` thats not printable too

**Comment by kotontrion** [comment]
> We should probably move this into overrides.ts

done. I also moved the Gio._promisify call from the hyprland service there, as this also messes with the prototype.

**Pull request merged**
