### PR TITLE
Add signal for fullscreen state in Hyprland service

### PR DESCRIPTION
**Pull request by matt1432**
I simply added a case in the _onEvent function to send a signal when the fullscreen state changes.

### CODE REVIEW

**Comment by Aylur** [comment]
it would also need a syncClient call because the `fullscreen` signal doesn't emit which client changed
```js
await this._syncClients()
``` 
also don't use a ternary for booleans
```js
argv[0] === '1' ? true : false // don't
argv[0] === '1' // just this
```

**Comment by matt1432** [comment]
I don't know if we should implement this in the service, but what bothers me about the fullscreen signal, is that it doesn't change whenever we leave the workspace where the fullscreen client is.

I know how I would do this in my ags config but i didn't know if you wanted to add it directly in the service.

For example, when fullscreen === 1 is received and then later on if the workspace changes, we call `hyprctl activewindow -j` to see if the activewindow is fullscreened. If not, we make an artificial fullscreen === 0 signal. We then do this at every workspace change until fullscreen === 0 is recieved.

**Comment by Aylur** [comment]
it is better to keep it consistent with the hyprland socket imo, fullscreen and workspace change is too different things, if the user wants to check for both, they can listen to both and make their logic accordingly

**Comment by matt1432** [comment]
Yeah that's fair. Is there anything else I should do for this PR?

**Comment by Aylur** [comment]
but now that you mention it, `hyprctl workspaces` also lists fullscreen, so we should sync that too, and then if you want both you can just listen to notify::worspaces

**Comment by matt1432** [comment]
So whenever there's a fullscreen signal, we want to sync both clients and workspaces?

**Comment by Aylur** [comment]
yes
```js
await this._syncClients();
await this._syncWorkspaces();
this.emit('fullscreen', argv[0] === '1');
```

**Comment by matt1432** [comment]
It's done

**Pull request merged**
